- stat:
    path: "{{ user_home }}/.nvm/nvm.sh"
  register: nvm_stat

- name: Download nvm installer
  get_url:
    url: "https://raw.githubusercontent.com/creationix/nvm/v{{ nvm_version }}/install.sh"
    dest: /tmp/nvm-install.sh
    mode: u+x
  when: not nvm_stat.stat.exists
  register: nvm_install_downloaded

- name: Execute the nvm-install.sh
  shell: /tmp/nvm-install.sh
  when: nvm_install_downloaded.changed

- name: Remove the nvm-install.sh
  file:
    path: /tmp/nvm-install.sh
    state: absent
  when: nvm_install_downloaded.changed
