- name: Setup local environment
  hosts: local
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "Sudo password"
      private: yes
  roles:
    - { role: dependencies, tags: ["dependencies"] }
    - { role: ssh, tags: ["ssh"] }
    - { role: git, tags: ["git"] }
    - { role: fish, tags: ["fish", "bootstrap"] }
    - { role: neovim, tags: ["neovim"] }
    - { role: tmux, tags: ["tmux"] }
    - { role: alacritty, tags: ["alacritty"] }
    - { role: nvm, tags: ["nvm"] }
    - { role: sdkman, tags: ["sdkman"] }
    - { role: bat, tags: ["bat"] }
    - { role: rust, tags: ["rust"] }
    - { role: go, tags: ["go"] }
