- name: Make sure ssh dir exists
  file:
    path: "{{ user_home }}/.ssh"
    state: directory

- name: Make sure ssh config is up to date
  copy:
    src: "config"
    dest: "{{ user_home }}/.ssh/config"
