[font]
size = 12.0

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[window.padding]
x = 10
y = 10

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001BF"

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001BB"

[shell]
program = "/usr/bin/tmux"
args = [
	"new-session",
	"-A",
	"-D",
	"-s",
	"main",
]	
