- name: Install git
  become: true
  pacman:
    name: git
    state: present

- name: Make sure gitconfig is up to date
  template:
    src: "gitconfig.j2"
    dest: "{{user_home}}/.gitconfig"
    backup: yes

- name: Install gitflow
  yay:
    name: gitflow-avh
    state: present
