- name: Install tmux
  pacman:
    name: tmux
    state: present

- name: Install tpm
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ user_home }}/.tmux/plugins/tpm"

- name: Make sure tmux.conf is up to date
  copy:
    src: "tmux.conf"
    dest: "{{ user_home }}/.tmux.conf"
