- name: Install alacritty
  become: true
  pacman:
    name: alacritty
    state: present

- name: Check if alacritty.yml already exists
  stat:
    path: "{{user_home}}/.config/alacritty/alacritty.yml"
  register: alacritty_yml_stat

- name: Backup alacritty.yml if it exists
  command: mv "{{user_home}}/.config/alacritty/alacritty.yml" "{{user_home}}/.config/alacritty/alacritty.yml.bak"
  args:
    creates: "{{user_home}}/.config/alacritty/alacritty.yml.bak"
  when: alacritty_yml_stat.stat.exists

- name: Make sure alacritty.yml is up to date
  file:
    src: "{{clone_folder}}/dotfiles/roles/alacritty/files/alacritty.yml"
    dest: "{{user_home}}/.config/alacritty/alacritty.yml"
    state: link
