- name: Install alacritty
  become: true
  pacman:
    name: alacritty
    state: present

- name: Make sure alacritty.yml is up to date
  copy:
    src: "alacritty.yml"
    dest: "{{ user_home }}/.config/alacritty/alacritty.yml"
